//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fangame_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string startScriptFilename {
            get {
                return ((string)(this["startScriptFilename"]));
            }
            set {
                this["startScriptFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string stopScriptFilename {
            get {
                return ((string)(this["stopScriptFilename"]));
            }
            set {
                this["stopScriptFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoFire {
            get {
                return ((bool)(this["autoFire"]));
            }
            set {
                this["autoFire"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int recentGamesMax {
            get {
                return ((int)(this["recentGamesMax"]));
            }
            set {
                this["recentGamesMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size oldWidth {
            get {
                return ((global::System.Drawing.Size)(this["oldWidth"]));
            }
            set {
                this["oldWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Completed")]
        public string foldernameForCompleted {
            get {
                return ((string)(this["foldernameForCompleted"]));
            }
            set {
                this["foldernameForCompleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zips")]
        public string foldernameForArchives {
            get {
                return ((string)(this["foldernameForArchives"]));
            }
            set {
                this["foldernameForArchives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\7-Zip\\7z.exe")]
        public string extractProgramFilename {
            get {
                return ((string)(this["extractProgramFilename"]));
            }
            set {
                this["extractProgramFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool deleteArchivesOnExtract {
            get {
                return ((bool)(this["deleteArchivesOnExtract"]));
            }
            set {
                this["deleteArchivesOnExtract"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startAutoScriptOnAppStart {
            get {
                return ((bool)(this["startAutoScriptOnAppStart"]));
            }
            set {
                this["startAutoScriptOnAppStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool extractArchivesOnStartup {
            get {
                return ((bool)(this["extractArchivesOnStartup"]));
            }
            set {
                this["extractArchivesOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool openStatsOnGameStart {
            get {
                return ((bool)(this["openStatsOnGameStart"]));
            }
            set {
                this["openStatsOnGameStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startAutoScriptOnGameStart {
            get {
                return ((bool)(this["startAutoScriptOnGameStart"]));
            }
            set {
                this["startAutoScriptOnGameStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool openStatsOnAppStart {
            get {
                return ((bool)(this["openStatsOnAppStart"]));
            }
            set {
                this["openStatsOnAppStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Completed Fangames")]
        public string spreadSheetnameForGoogle {
            get {
                return ((string)(this["spreadSheetnameForGoogle"]));
            }
            set {
                this["spreadSheetnameForGoogle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal startRowForSheet {
            get {
                return ((decimal)(this["startRowForSheet"]));
            }
            set {
                this["startRowForSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal startColumnForSheet {
            get {
                return ((decimal)(this["startColumnForSheet"]));
            }
            set {
                this["startColumnForSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool driveSheetInsertOn {
            get {
                return ((bool)(this["driveSheetInsertOn"]));
            }
            set {
                this["driveSheetInsertOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool hideStatsOnGameExit {
            get {
                return ((bool)(this["hideStatsOnGameExit"]));
            }
            set {
                this["hideStatsOnGameExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showAddCurrentCompletedButton {
            get {
                return ((bool)(this["showAddCurrentCompletedButton"]));
            }
            set {
                this["showAddCurrentCompletedButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point statsWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["statsWindowLocation"]));
            }
            set {
                this["statsWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool moveCompletedGamesAway {
            get {
                return ((bool)(this["moveCompletedGamesAway"]));
            }
            set {
                this["moveCompletedGamesAway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point oldPosition {
            get {
                return ((global::System.Drawing.Point)(this["oldPosition"]));
            }
            set {
                this["oldPosition"] = value;
            }
        }
    }
}
